Packer id

diff --git a/.github/workflows/packerBuild-workflow.yml b/.github/workflows/packerBuild-workflow.yml
--- a/.github/workflows/packerBuild-workflow.yml
+++ b/.github/workflows/packerBuild-workflow.yml
@@ -50,67 +50,102 @@ jobs:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           AWS_DEFAULT_REGION: us-east-1
-      
-      - name: Copying ami Artifacts and Launching Template
-        working-directory: ../webapp
+deploy:
+  name: deploy AMI
+  runs-on: ubuntu-latest
+    needs: build-and-deploy
+
+    env:
+      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+      AWS_DEFAULT_REGION: us-east-1
+
+    steps:
+      - name: checkout
+        uses: actions/checkout@v3
+
+      - name: Setup Demo Environment
         run: |
-            AMI_ID=$(jq -r '.builds[-1].artifact_id' manifest.json | cut -d ":" -f2)
-            echo $AMI_ID
-            LT_ID=$(aws ec2 describe-launch-templates --launch-template-name launchTemplate | jq '.LaunchTemplates[].LaunchTemplateId')
-            LT_ID="${LT_ID%\"}"
-            LT_ID="${LT_ID#\"}"
-            echo $LT_ID
-            aws ec2 create-launch-template-version --launch-template-id "$LT_ID" --version-description WebVersion2 --source-version 1 --launch-template-data "ImageId=$AMI_ID"
-            aws autoscaling update-auto-scaling-group --auto-scaling-group-name asg_launch_config --launch-template LaunchTemplateId=$LT_ID,Version='$Latest'
-        env:
-          AWS_ACCESS_KEY_ID_DEMO: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY_DEMO: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-      
-          
-      - name: Refreshing Instances
-        run: aws autoscaling start-instance-refresh --auto-scaling-group-name asg_launch_config
-        env:
-          AWS_ACCESS_KEY_ID_DEMO: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY_DEMO: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-      
-      
-      - name: Wait for Instance Refresh to complete
+          export AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}}
+          export AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}}
+
+      - name: Get Auto Scaling Group and Launch Template
+        id: get_asg_and_lt
         run: |
-            TIMEOUT=900 
-            START_TIME=$(date +%s)
+          LT_NAME_PREFIX="launchTemplate-"
 
-            while true; do
-              CURRENT_TIME=$(date +%s)
-              ELAPSED_TIME=$((CURRENT_TIME - START_TIME))
+          LT_NAME=$(aws ec2 describe-launch-templates --query "LaunchTemplates[?starts_with(LaunchTemplateName, '${LT_NAME_PREFIX}')].LaunchTemplateName" --output text)
 
-              # Check if the timeout has been reached
-              if [ "$ELAPSED_TIME" -ge "$TIMEOUT" ]; then
-                  echo "Instance Refresh timed out. Exiting with an error."
-                  exit 1
-              fi
+          if [ -z "$LT_NAME" ]; then
+            echo "No Launch Template found with the specified prefix."
+            exit 1
+          fi
 
-              # Check the status of the instance refresh
-              INSTANCE_REFRESH_STATUS=$(aws autoscaling describe-instance-refreshes --auto-scaling-group-name asg_launch_config | jq -r '.InstanceRefreshes[0].Status')
-                echo "Instance Refresh Status: $INSTANCE_REFRESH_STATUS"
+          ASG_NAME=$(aws autoscaling describe-auto-scaling-groups --query "AutoScalingGroups[?contains(LaunchTemplate.LaunchTemplateName, '${LT_NAME}')].AutoScalingGroupName" --output text)
 
-              # Break out of the loop if the instance refresh is completed (either Successful or Failed)
-              if [ "$INSTANCE_REFRESH_STATUS" == "Successful" ] || [ "$INSTANCE_REFRESH_STATUS" == "Failed" ]; then
-                break
-              fi
+          if [ -z "$ASG_NAME" ]; then
+            echo "No Auto Scaling Group found using the Launch Template."
+            exit 1
+          fi
 
-              sleep 30
-            done
+          ASG_ID=$(aws autoscaling describe-auto-scaling-groups --auto-scaling-group-names $ASG_NAME --query 'AutoScalingGroups[0].AutoScalingGroupARN' --output text | cut -d':' -f 6)
+          LT_ID=$(aws ec2 describe-launch-templates --launch-template-names $LT_NAME --query 'LaunchTemplates[0].LaunchTemplateId' --output text)
 
-            # Set the GitHub Actions workflow status based on the instance refresh status
-            if [ "$INSTANCE_REFRESH_STATUS" == "Successful" ]; then
-              echo "Instance Refresh successful."
-              exit 0  # Exit with success status
-            else
-              echo "Instance Refresh failed. Exiting with an error."
-              exit 1  # Exit with error status
-            fi
-        shell: bash
-        env:
-          AWS_ACCESS_KEY_ID_DEMO: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY_DEMO: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          echo "Auto Scaling Group Name: $ASG_NAME"
+          echo "Auto Scaling Group ID: $ASG_ID"
+          echo "Launch Template Name: $LT_NAME"
+          echo "Launch Template ID: $LT_ID"
 
+          AMI_ID=$(aws ec2 describe-images \
+          --executable-users ${{secrets.USER}} \
+          --query 'Images | sort_by(@, &CreationDate) | [-1].ImageId' \
+          --filters "Name=name,Values=custom-debian-Raj*" \
+          --output text 
+          )
+
+          aws ec2 create-launch-template-version --launch-template-id $LT_ID \
+          --version-description "Latest AMI version" \
+          --source-version 1 \
+          --launch-template-data "ImageId=$AMI_ID"
+
+          echo "::set-output name=asg_name::$ASG_NAME"
+          echo "::set-output name=asg_id::$ASG_ID"
+          echo "::set-output name=lt_name::$LT_NAME"
+          echo "::set-output name=lt_id::$LT_ID"
+
+      - name: Trigger Auto Scaling Group Instance Refresh with Latest Launch Template
+        run: |
+          ASG_NAME="${{ steps.get_asg_and_lt.outputs.asg_name }}"
+
+          LT_NAME_PREFIX="launchTemplate-"
+
+          LT_NAME=$(aws ec2 describe-launch-templates --query "LaunchTemplates[?starts_with(LaunchTemplateName, '${LT_NAME_PREFIX}')].LaunchTemplateName" --output text)
+
+          # Get the latest version of the Launch Template
+          LATEST_LT_VERSION=$(aws ec2 describe-launch-templates --launch-template-names ${LT_NAME} --query "LaunchTemplates[0].LatestVersionNumber" --output text)
+
+
+          # Update the Auto Scaling Group with the latest Launch Template version
+          aws autoscaling update-auto-scaling-group --auto-scaling-group-name $ASG_NAME --launch-template "LaunchTemplateName=$LT_NAME,Version=$LATEST_LT_VERSION"
+
+          # Trigger an instance refresh with the latest Launch Template as default
+          aws autoscaling start-instance-refresh --auto-scaling-group-name $ASG_NAME --strategy Rolling
+
+      - name: Wait for Auto Scaling Group Instance Refresh Completion
+        run: |
+          ASG_NAME="${{ steps.get_asg_and_lt.outputs.asg_name }}"
+          REFRESH_STATUS=""
+          while [[ "$REFRESH_STATUS" != "Successful" && "$REFRESH_STATUS" != "Failed" ]]; do
+            REFRESH_STATUS=$(aws autoscaling describe-instance-refreshes --auto-scaling-group-name $ASG_NAME --query 'InstanceRefreshes[0].Status' --output text)
+
+            echo "Instance Refresh Status: $REFRESH_STATUS"
+            sleep 15
+          done
+            
+          # Check the instance refresh status and fail the workflow if it failed
+          if [[ "$REFRESH_STATUS" == "Failed" ]]; then
+            echo "Instance refresh failed. Workflow failed."
+            exit 1
+          else
+            echo "Instance refresh completed successfully."
+          fi
